name: Publish Image Using Commit Hash

on:
  push:
    #branches:
    #  - master

jobs:
  build-spark:
    name: Publish Spark Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Ensure we can build spark
      run: SPARK_IMAGE_TAG=$GITHUB_SHA ./build_spark.sh