name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - master

jobs:
  publish-spark:
    name: Publish Spark Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Install R rmarkdown
      run: Rscript -e "install.packages('rmarkdown', repos = 'http://cran.us.r-project.org')"
    - name: Install R knitr
      run: Rscript -e "install.packages('knitr', repos = 'http://cran.us.r-project.org')"
    - name: Install R sparklyr
      run: Rscript -e "install.packages('sparklyr', repos = 'http://cran.us.r-project.org')"
    - name: Install python3-setuptools
      run: sudo apt-get install python3-setuptools
    - name: Log into registry
      run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
    - name: Build image
      run: SPARK_IMAGE_TAG=$GITHUB_SHA ./build_spark.sh
      env:
        SPARK_VERSION: "3.1.2"
        HADOOP_VERSION: "3.3.1"
    - name: Push image
      run: docker push ferlabcrsj/spark:$GITHUB_SHA
  publish-hive:
    name: Publish Hive Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
    - name: Build image
      run: docker build --build-arg METASTORE_VERSION=3.0.0 -t ferlabcrsj/hive-metastore:$GITHUB_SHA .
      working-directory: hive_metastore
    - name: Push image
      run: docker push ferlabcrsj/hive-metastore:$GITHUB_SHA
  publish-zeppelin:
    name: Publish Zeppelin Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
    - name: Build image
      run: docker build -t ferlabcrsj/zeppelin:$GITHUB_SHA .
      working-directory: zeppelin
    - name: Push image
      run: docker push ferlabcrsj/zeppelin:$GITHUB_SHA