name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - master

jobs:
  publish-spark:
    name: Publish Spark Image Using Commit Hash
    environment: publication
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - uses: r-lib/actions/setup-r@v2
    - name: Install R rmarkdown
      run: Rscript -e "install.packages('rmarkdown', repos = 'http://cran.us.r-project.org')"
    - name: Install R knitr
      run: Rscript -e "install.packages('knitr', repos = 'http://cran.us.r-project.org')"
    - name: Install R sparklyr
      run: Rscript -e "install.packages('sparklyr', repos = 'http://cran.us.r-project.org')"
    - name: Install python3-setuptools
      run: sudo apt-get install python3-setuptools
    - name: Log into registry
      run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
    - name: Build image
      run: SPARK_IMAGE_TAG=$GITHUB_SHA ./build_spark.sh
      #Temporary env to accomodate temporary minio internal CA
      env:
        MAVEN_OPTS: "-Xms256m -Xmx2048m -Xss10m"
        MINIO_CA_CERT: ${{ secrets.MINIO_CA_CERT }}
    - name: Push image
      run: docker push ferlabcrsj/spark:$GITHUB_SHA
  publish-hive:
    name: Publish Hive Image Using Commit Hash
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Push the image on the registry
      uses: Ferlab-Ste-Justine/action-push-image@v2
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/hive-metastore
        tag_format: "{sha}-{timestamp}"
        location: hive_metastore
        dockerfile: hive_metastore/Dockerfile
  publish-zeppelin:
    name: Publish Zeppelin Image Using Commit Hash
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
    - name: Build image
      run: docker build -t ferlabcrsj/zeppelin:$GITHUB_SHA .
      working-directory: zeppelin
    - name: Push image
      run: docker push ferlabcrsj/zeppelin:$GITHUB_SHA