name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - master

jobs:
  publish-spark:
    name: Publish Spark Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u chusj --password-stdin
    - name: Build image
      run: SPARK_IMAGE_TAG=$GITHUB_SHA ./build_spark.sh
    - name: Push image
      run: docker push chusj/spark:$GITHUB_SHA
  publish-hive:
    name: Publish Hive Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u chusj --password-stdin
    - name: Build image
      run: docker build --build-arg METASTORE_VERSION=3.0.0 -t chusj/hive-metastore:$GITHUB_SHA .
      working-directory: hive_metastore
    - name: Push image
      run: docker push chusj/hive-metastore:$GITHUB_SHA
  publish-zeppelin:
    name: Publish Zeppelin Image Using Commit Hash
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u chusj --password-stdin
    - name: Build image
      run: docker build -t chusj/zeppelin:$GITHUB_SHA .
      working-directory: zeppelin
    - name: Push image
      run: docker push chusj/zeppelin:$GITHUB_SHA