name: Publish Images Using Dependency Version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-spark:
    name: Publish Spark Image
    environment: publication
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install R rmarkdown
        run: Rscript -e "install.packages('rmarkdown', repos = 'http://cran.us.r-project.org')"
      - name: Install R knitr
        run: Rscript -e "install.packages('knitr', repos = 'http://cran.us.r-project.org')"
      - name: Install R sparklyr
        run: Rscript -e "install.packages('sparklyr', repos = 'http://cran.us.r-project.org')"
      - name: Install python3-setuptools
        run: sudo apt-get install python3-setuptools
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build spark
        run: ./build_spark.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Asset
        id: upload-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spark-3.1.2-bin-hadoop-3.3.1.tgz
          asset_name: spark-3.1.2-bin-hadoop-3.3.1.tgz
          asset_content_type: application/gzip